_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.10
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
B:
    value: 2
C:
    value: 5
S:
    value: 7
architecture:
    value:
        - - 7
          - 64
          - 2
          - 3
        - maxpool
        - - 3
          - 192
          - 1
          - 1
        - maxpool
        - - 1
          - 128
          - 1
          - 0
        - - 3
          - 256
          - 1
          - 1
        - - 1
          - 256
          - 1
          - 0
        - - 3
          - 512
          - 1
          - 1
        - maxpool
        - - - 1
            - 256
            - 1
            - 0
          - - 3
            - 512
            - 1
            - 1
          - 4
        - - 1
          - 512
          - 1
          - 0
        - - 3
          - 1024
          - 1
          - 1
        - maxpool
        - - - 1
            - 512
            - 1
            - 0
          - - 3
            - 1024
            - 1
            - 1
          - 2
        - - 3
          - 1024
          - 1
          - 1
        - - 3
          - 1024
          - 2
          - 1
        - - - 3
            - 1024
            - 1
            - 1
          - 2
batch_size:
    value: 128
confidence_threshold:
    value: 0.5
device:
    value: cpu
epochs:
    value: 35
image_resize:
    value: 124
iou_threshold:
    value: 0.5
lambda_coord:
    value: 5
lambda_noobj:
    value: 0.5
learning_rate:
    value: 0.001
